---
title: "Lab1Assignment"
output: html_document
date: "2024-10-25"
---

# ***Advanced Geovis Lab 1***
```{r}
library(ggplot2)
library(sf)
library(tidyverse)
library(conflicted)
```

```{r}
boulder <- st_read("C:/Users/jdursing/Downloads/lab1/BoulderSocialMedia/BoulderSocialMedia.shp")
```
```{r}
boulder
```

```{r}
boulder = st_transform(boulder, 26753)
ggplot() +
  geom_sf(data = boulder, aes(color = extent),
          fill = NA, alpha = 0.2) +
  theme_bw()
```

```{r}
boulder = st_transform(boulder, 26753)
ggplot() +
  geom_sf(data = boulder, aes(color = extent),
          fill = NA, alpha = 0.2) +
  scale_colour_gradientn(colours = terrain.colors(10)) +
  theme_bw()
```

```{r}
boulder %>%
  mutate (high_dis = ifelse(Hydro_dis >= 1800, TRUE, FALSE))%>%
ggplot() +
  geom_sf(aes(color = high_dis), 
          fill = NA, alpha = 0.2) +
  theme_bw()
```

```{r}
boulder %>%
 dplyr:: filter(DB == 'Pano' | DB == 'Flickr') %>%
  ggplot(aes(x=DB, y=Bike_dis)) + 
  geom_boxplot()
```

```{r}
library(ggspatial)
library(viridis)
```

```{r}
ggplot() +
  geom_sf(data = boulder, aes(color=PT_Elev),
          fill = NA, alpha = 0.2) + scale_colour_gradientn(colors = plasma(10))
```

```{r}
summary(boulder$DB)
summary(boulder$PT_Elev)
```

```{r}
p <- ggplot() +
  annotation_spatial(boulder) + 
  layer_spatial(boulder, aes(col=DB))
p + scale_color_brewer(palette = "Dark2")
```

```{r}
library(tmap)
```

```{r}
tm_shape(boulder) + 
  tm_symbols(col='PT_Elev',
             style='quantile',
             palette='YlOrRd',
             border.lwd = NA,
             size=0.1)
```

```{r}
data("World")
tm_shape(World) +
  tm_polygons("gdp_cap_est", style='quantile', legend.title="GDP Per Capita Estimate")
```

```{r}
tmap_mode("view")
```

```{r}
tm_shape(World) +
  tm_polygons("gdp_cap_est", style='quantile', legend.title="GD Per Capita Estimate")
```

